# Generated by Django 4.2.29 on 2026-09-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('pickup', models.CharField(max_length=180)),
                ('destination', models.CharField(max_length=180)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('passengers', models.PositiveSmallIntegerField(default=2)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
